# Generated by Django 4.1.2 on 2022-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
